default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    learning_rate_schedule: linear
    max_steps: 5.0e4
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
            
RollerBallBrain:
    batch_size: 10
    buffer_size: 100
    
stage0:
    batch_size: 10
    buffer_size: 100
    max_steps: 3.0e4
    
stage1:
    batch_size: 10
    buffer_size: 100
    max_steps: 3.0e4

stage2:
    batch_size: 32
    buffer_size: 256
    max_steps: 5.0e5
    hidden_units: 128
    num_layers: 3
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        curiosity:
            strength: 0.02
            gamma: 0.99
            encoding_size: 256
    
stage3:
    batch_size: 10
    buffer_size: 100
    hidden_units: 64
    num_layers: 3
    max_steps: 3.0e4
    
stage4:
    learning_rate: 1.0e-4
    epsilon: 0.3
    batch_size: 32
    buffer_size: 256
    max_steps: 5.0e4
    num_layers: 1
    hidden_units: 256
    
stage5:
    batch_size: 32
    normalize: false
    num_layers: 1
    beta: 5.0e-3
    buffer_size: 256
    hidden_units: 256
    max_steps: 5.0e4
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.9
stage6:
    batch_size: 10
    buffer_size: 100
    max_steps: 5.0e4

stage6Test:
    batch_size: 10
    buffer_size: 100
    max_steps: 5.0e4

            
TextureRollerBallBrain:
    batch_size: 10
    buffer_size: 100
